### ISSUE TITLE
Unused variable warning for types with guards

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#25]
It seems that referencing a custom type that has a guard clause results in an unused variable compiler warning. A stripped down example:

```elixir
@type! some_type :: value :: any() when is_binary(value)
```

```elixir
@spec! some_fun(some_type()) :: binary()
def some_fun(value) do
  value
end
```

The resulting warning...

```
warning: variable "some_type" is unused (if the variable is not meant to be used, prefix it with an underscore)
```

This seems to have been introduced in 0.2.1 as I'm not seeing the warnings in 0.2.0.

**Comment by baldwindavid** [comment]
Okay, I saw the release notes on ElixirForum, but thought that was all part of the `wrap_with_gen` PR.

I now see #24 with a description of usage. I don't get the compiler warning when referencing the type name directly in the guard now. The syntax also feels more natural.

However, it does appear that the warning still occurs when the type name is not referenced in the guard. The example in the docs does result in a warning...

```elixir
@type! sorted_pair :: {lower :: number(), higher :: number()} when lower <= higher
```

**Comment by Qqwy** [comment]
Thank you for this bug report. I am fairly certain that the problem lies in the type-checking code that the type guard generates, because here all named types are filled as variables so they can be used in the guard.
https://github.com/Qqwy/elixir-type_check/blob/master/lib/type_check/builtin/guarded.ex#L68

I think the proper approach here is to disable the warnings by setting `generated: true` at the appropriate location of the AST that is being built.

**Comment by Qqwy** [comment]
@baldwindavid Does this still happen in the current version of the library?

**Comment by baldwindavid** [comment]
Just updated to 0.3.1 and the warning still seems to appear.
