### ISSUE TITLE
Support binary pattern-matches containing size-references like `<<_ :: size>>`

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#26]
I think the majority of the unsupported functionality is represented in issues other than binary pattern-matches containing size-references like `<<_ :: size>>` so I am adding here.

A practical example of where this would be useful is for specifying a UUID. I'm currently using the following custom type as a placeholder.

```elixir
@type! uuid :: utf8_binary()
```

`utf8_binary` itself is a placeholder until something like `String.t` is introduced. If binary pattern-matches with size references were supported I believe this could be changed to...

```elixir
@type! uuid :: <<_::128>>
```

This is based on the type from `Ecto.UUID` at https://hexdocs.pm/ecto/Ecto.UUID.html#t:raw/0

**Comment by Qqwy** [comment]
This would be very useful. 

The reason it is not yet part of TypeCheck right now, is that doing all the binary pattern-matching logic is quite a bit of work. There are quite a number of different constructs one might use inside a binary pattern match, and for each of then we need to be able to _both_ match on it (not so hard as we can use Elixir's existing syntax for that) _and_ write a property-testing generator for it (this is the hard part).

Nonetheless, maybe we can start by already adding some simple cases like the `<<_ :: size >>`.

**Comment by Qqwy** [comment]
Different than from what I thought previously, binary typespecs actually do not support 'all of binary pattern matching' but instead only the patterns:

```
      | <<>>                          # empty bitstring
      | <<_::size>>                   # size is 0 or a positive integer
      | <<_::_*unit>>                 # unit is an integer from 1 to 256
      | <<_::size, _::_*unit>>
```

which definitely seems more manageable to support, both as a type-check and also to generate. :slightly_smiling_face:

**Comment by Qqwy** [comment]
It is possible to write a custom check for it today, such as:

```elixir
defmodule MyUUID do
  use TypeCheck
  @type! t() :: (bits :: binary()) when bit_size(bits, 288))
end
```

Such a type could be used in checks, but not in spectests/other property-tests because the generator will be extremely unlikely to generate correct binaries, resulting in a 'too much data filtered' error.
A custom StreamData generator could be provided as well, of course. But I digress :slightly_smiling_face: .

---

Indeed, it is rather common to use these types. It would be nice if TypeCheck could easily operate within a project using Ecto,  Phoenix or other common libraries.

Tackling this issue will probably happen very soon (sometime in the next week) as it is next on the changelog list.
