### ISSUE TITLE
`warning: "else" clauses will never match because all patterns in "with" will always match`

### ISSUE THREAD

**Issue by Maxximiliann** [Qqwy/elixir-type_check#40]
After adding TypeSpec to a module these warnings started to appear: 

`warning: "else" clauses will never match because all patterns in "with" will always match`

Removing TypeSpec does away with the warnings, though. 

We'd like to keep utilizing TypeSpec so how do we address these warnings?

**Comment by Qqwy** [comment]
This is a great question!

First, this warning happens because TypeCheck adds type-checking code to functions that have an `@spec!`. This code is generated automatically. For certain combinations of nested types (mainly when using e.g. `any()` as one of the nested types), certain pattern matches will always happen to match, so an `else` is never reached.

In and of itself this is not a problem: the Elixir/Erlang compiler will usually optimize this away.
The warning itself is also not a problem, as it was created by generated code rather than code you wrote by hand.

Of course, many people use `--warnings-as-errors` in their projects to make sure all developers write clean code. Also, it is annoying to receive warnings from your dependencies, as it makes it look like either the dependency contains a problem or you are using it improperly.

In a perfect world, TypeCheck would handle all of these special cases and always create 100% clean Elixir code that we'd otherwise be written by hand. However, I strongly doubt this is worth it, as it
- will take a lot of time and effort to get right;
- will make the code of TypeCheck itself (the code that generates the type-checking code) very complicated and difficult to maintain.

The most pragmatic solution is probably for TypeCheck to find a way to silence this and similar warnings, although I don't know wether Elixir supports this: `quote generated: true` is already used by a lot of code snippets in TypeCheck, but Elixir gives it a big caveat in the documentation: 
> Currently it only works on special forms (for example, you can
    annotate a case but not an if).

---

For your particular case: could you share an example of the code that produces the warning in your case? We might at least be able to address this particular warning (and maybe a couple of other common warnings) as a 'shorter-term' solution.

**Comment by Maxximiliann** [comment]
Thank you for your comprehensive response :)

Since it seems we can just ignore these warnings we'll do just that. Thanks again!
