### ISSUE TITLE
** (FunctionClauseError) no function clause matching in Inspect.Stream.inspect/2    

### ISSUE THREAD

**Issue by Maxximiliann** [Qqwy/elixir-type_check#45]
```
defmodule Laboratory do
  use TypeCheck

  @spec! foo(%Stream{}) :: list
  def foo (random_sequence) do
    Enum.take(random_sequence, 100)
  end

  @spec! baz() :: %Stream{}
  def baz() do

    :rand.seed(:exrop, {1, 2, 3})

    random_sequence =
    Stream.repeatedly(&:rand.uniform/0)

    foo(random_sequence)
  end
end
```

Error: 
```
iex(1)> Laboratory.baz
** (FunctionClauseError) no function clause matching in Inspect.Stream.inspect/2    
    
    The following arguments were given to Inspect.Stream.inspect/2:
    
        # 1
        %Inspect.Error{
          message: "got FunctionClauseError with message \"no function clause matching in Inspect.Stream.inspect/2\" while inspecting %{__struct__: Stream}"
        }
    
        # 2
        %Inspect.Opts{
          base: :decimal,
          binaries: :infer,
          char_lists: :infer,
          charlists: :infer,
          custom_options: [],
          inspect_fun: &TypeCheck.Protocols.Inspect.inspect/2,
          limit: 50,
          pretty: false,
          printable_limit: 4096,
          safe: true,
          structs: true,
          syntax_colors: [],
          width: 80
        }
    
    Attempted function clauses (showing 1 out of 1):
    
        def inspect(%{enum: enum, funs: funs}, opts)
    
    (elixir 1.10.3) lib/stream.ex:1637: Inspect.Stream.inspect/2
    (type_check 0.3.1) lib/type_check/protocols/inspect.ex:52: TypeCheck.Inspect.inspect/2
    (type_check 0.3.1) lib/type_check/protocols/inspect.ex:57: TypeCheck.Inspect.inspect_binary/2
    (type_check 0.3.1) lib/type_check/type_error/default_formatter.ex:212: TypeCheck.TypeError.DefaultFormatter.do_format/1
    (type_check 0.3.1) lib/type_check/type_error/default_formatter.ex:6: TypeCheck.TypeError.DefaultFormatter.format/2
    (type_check 0.3.1) lib/type_check/type_error.ex:55: TypeCheck.TypeError.exception/1
    (arbit 0.1.0) lib/Laboratory.ex:1: Laboratory.foo/1
    (arbit 0.1.0) lib/Laboratory.ex:9: Laboratory.baz/0
```

**Comment by Qqwy** [comment]
For some reason `%Stream{}` is interpreted by TypeCheck as `%{__struct__: Stream}` rather than as a full-fledged Stream struct that has the keys that Stream actually uses.

The error is the same as when calling
```
Inspect.Stream.inspect(%{__struct__: Stream}, %Inspect.Opts{})
```
manually.

I'll dig deeper to find out where this is caused. There's probably a place where TypeCheck constructs the structs incorrectly and should use `struct(Stream)` instead.

In the meantime, as a workaround you could explicitly define and use the following type:
(either in the same module or of course in a separate module; you can then re-use the type in multiple places).

```
  @type! stream() :: %{__struct__: Stream, enum: any(), funs: list(function()), accs: list(), done: any} | function()
```

which I've tested to work with your example:

```
defmodule Labratory2 do
  use TypeCheck

  @type! stream() :: %{__struct__: Stream, enum: any(), funs: list(function()), accs: list(), done: any} | function()

  @spec! foo(stream()) :: list
  def foo (random_sequence) do
    Enum.take(random_sequence, 100)
  end

  @spec! baz() :: stream()
  def baz() do

    :rand.seed(:exrop, {1, 2, 3})

    random_sequence =
      Stream.repeatedly(&:rand.uniform/0)

    foo(random_sequence)
  end
end
```

**Comment by Qqwy** [comment]
It is now possible to use the type `%Stream{}` directly, which will be printed as `#TypeCheck.Type< #Stream<[...]> >`.

_However_, this is not recommended, for two reasons:

1. A type specification like `%Stream{}` will match exactly `%{__struct__: Stream}` which actually does not contain the fields of a real Stream struct. (And this is the main reason for the  error earlier).
2. Streams are not meant to be used in that way. Not only is the Stream struct itself private (and not even exposed as an opaque type), the Stream module's `moduledoc` states:

> Note the functions in this module are guaranteed to return enumerables. Since enumerables can have different shapes (structs, anonymous functions, and so on), the functions in this module may return any of those shapes and this may change at any time. For example, a function that today returns an anonymous function may return a struct in future releases.

So I suggest either using the form that I mentioned above (which might however still fail when a stream-function happens to return an actual enumerable rather than a 100% lazy result, which, according to above documentation is allowed), 
or instead (as soon as PR #44 is merged) using `Enum.t` to talk about _any_ Enumerable including streams.

**Comment by Maxximiliann** [comment]
Interesting. Thanks for all your effort. What's your ETA on PR #44?

**Comment by Qqwy** [comment]
> What's your ETA on PR #44?

It very much depends on how much spare time I'll end up having the next week. I hope to be able to finish it either this or next week-end, but I can't give you a hard promise :man_shrugging: .
