### ISSUE TITLE
Comparison with Norm a bit out of date

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#51]
I think this comparison between TypeCheck and Norm is a bit out of date... https://github.com/Qqwy/elixir-type_check/blob/master/Comparing%20TypeCheck%20and%20Norm.md

For instance, it looks like it's referring to `spec` rather than `@spec!`.

I had someone ask me the difference between them today and I was going to link to this, so noticed it. It's a good comparison to have.

**Comment by Qqwy** [comment]
Thank you very much for pointing that out!

I have updated the guide's code snippets and also in some places content, as some new TypeCheck features have since been introduced (more support for Elixir's builtin types, typespecs).

The updated guide can be read here on GitHub, but also [as part of TypeCheck's documentation pages](https://hexdocs.pm/type_check/comparing-typecheck-and-norm.html).
