### ISSUE TITLE
Performance / Disabling Per-environment 

### ISSUE THREAD

**Issue by baldwindavid** [Qqwy/elixir-type_check#52]
This has been [discussed somewhat](https://elixirforum.com/t/typecheck-fast-and-flexible-runtime-type-checking-for-your-elixir-projects/32886/4?u=baldwindavid), but wondering how this might impact a large codebase. I believe there was also some discussion of allowing the checks to be disabled in production to avoid any extra cost. Perhaps an option like this would be a nice generalized way to specify whether checks could be disabled at runtime.

```elixir
use TypeCheck, enable_runtime_checks: mix.env != :prod # default `true`
```

**Comment by Qqwy** [comment]
This was already in the changelog, but now that spectests and the majority of Elixir's builtin types are supported, it definitely is time to start working on this :muscle: .

I very much like the name you gave the option :+1: .

One more idea which I have is to have a `runtime_check_depth:` option (which defaults to `:infinity`), that works as follows:
- If runtime checks are disabled, it does nothing.
- If runtime checks are enabled, it will only perform runtime checks up to the given depth. (The depth is decreased by one every time we move from checking a list/map/tuple to checking the contained elements.) After this, it will let any value pass.
  This means that once depth 1 is reached:
  - Lists of fixed length will check whether the given value is a proper list with the expected length, but we will not check the types of the elements 
  - Lists of varying length will check whether the given value is a proper list, but we will not check the types of the elements
  - Maps with fixed keys (such as structs) will check whether the given value is a map and whether all required keys are there, but will not check the types of the values.
  - Maps with varying keys will check whether the given value is a map but will not check the types of the key-value pairs.
  - Tuples will check whether the given value is a tuple (of the expected arity) but will not check the types of the elements
  - etc.

The idea behind this is that if you have a deeply nested tree of datastructures, or a large collection, it is wasteful to check all types all the way to the leaves and then when we do something with the individually contained elements, check them again.
Instead, we can limit the depth on the outermore checks so that we only check for e.g. a single 'layer' in the tree/collection at a time, keeping the checks fast (i.e. at only a constant-time overhead over calling a function with checks fully disabled).

This is obviously not a replacement for `:enable_runtime_checks` but an extra feature on top that could be useful for many (but not all) use-cases. What do you think?

**Comment by Qqwy** [comment]
Thanks for your reply!

> The `runtime_check_depth` makes sense as an option. I'm _probably_ less interested in messing with this value, but understand it could be valuable in some situations. I would likely just have a shared module that brings in TypeCheck and custom types and then `use` in other modules rather than configuring per module. As long as the default is `:infinity` though, it sounds good to me.

:+1: 

---

> Related to depth, I wanted to clarify something. [...]

I think my explanation was not very clear. Maybe an example explains it better.
Say you have the following spec:

```
defmodule User
@type! t :: %User{age: integer(), name: String.t()}
@spec! normalize({:ok, list(t()))) :: list(t())
```

Then at the following depts, it will be seen as:

- 0: `normalize(any()) :: any()`
- 1: `normalize({any(), any()}) :: list(any())`
- 2: `normalize({:ok, list(any())}) :: list(%User{age: any(), name: any()})`
- 3: `normalize({:ok, list(%User{age: any(), name: any()})}) :: list(%User{age: integer(), name: String.t()})`
- 4: `normalize({:ok, %User{age: integer(), name: String.t()}}) :: list(%User{age: integer(), name: String.t()})`
- 5 (and above): The same as 4.

For collections, rather than only looking at the first 'depth' elements, we look at the whole shape of the collection. The depth is not influenced by the size of the collection, only by the 'dimension' or 'level' of the collection or tree. So a list is one level deep, a list-of-lists is two levels deep, a list-of-tuples is also two levels deep, and a map-in-a-map-in-a-map would be three levels deep.

**Comment by baldwindavid** [comment]
Thanks, yes, the depth explanation totally makes sense. I was more thinking that perhaps the depth would only apply for remote types, such that you can trust that the spec typed above the function would be checked. So even with a depth set to 0, something like `{:ok, User.t()}` (when NOT in the User module) would check that it receives a tuple with the first element being :ok and that the second element is a user struct. However, `User` being a remote type, that depth comes into play (which would be far past 0 at that point) and none of the `User` attributes would be checked. Regardless, I'm making too much fuss of a feature I'm personally unlikely to use, so the way you have explained it is completely fine. haha

Regarding collections, I should have more clearly separated that question from the questions about depth. Let's take depth out of the equation and just assume it is set to `:infinity`. My concern was that for a spec like `[User.t()] :: [User.t()]` that passing a list of 10,000 User structs and checking that all of them were actually User structs on the way in and the way out might be a drag on performance. Do you have any thoughts on how much or how little concern I should have on that?

**Comment by Qqwy** [comment]
I actually really like the idea of having it stop on remote types.

One way or the other, the depth functionality needs more thought.
But for now, I'll go ahead and implement the general mechanism to choose whether the runtime checks are enabled/disabled per environment. :-)
