### ISSUE TITLE
Rethink approach to fixed-list-syntax

### ISSUE THREAD

**Issue by Qqwy** [Qqwy/elixir-type_check#8]
TypeCheck allows for fixed-list types like `[1, 2]`, which Elixir's builtin Typespecs do not allow.
On the other hand, syntaxes like `[type, ...]` are not supported at all, and `[type]` means something different in TypeCheck from the builtin Typespecs.

While this is a nice feature to have, it might also be confusing for some.

So this requires some thought.

Maybe we can warn on usage of literal lists, always preferring people to use `list(...)` or `fixed_list(...)` instead?

**Comment by Qqwy** [comment]
On the other hand, the only truly ambiguous case is `[type]`. We might warn only for that case. `[type1, type2]` (and longer) is clearly a 'fixed list' that is only supported with TypeCheck, and `[]` means the same thing for both builtin Typespecs and TypeCheck.

**Comment by baldwindavid** [comment]
I hadn't brought TypeCheck into a project in awhile and today this was the first thing that bit me. I might be wrong, but this feels like a barrier to adoption if other codebases are already making use of or expecting `[type]` to work how it does with regular typespecs. I would probably lean toward removing the fixed list "shorthand" altogether to eliminate confusion, especially since you already have the explicit `fixed_list`.

I know that any friction I feel in using TypeCheck nearly always deals with discrepancies between it and the typespecs listed at https://hexdocs.pm/elixir/1.12/typespecs.html

If I were to list in order the kinds of issues that result in the most confusion for me:
1. If something in regular typespecs also exists in TypeCheck, but works differently (e.g. `[type]`)
2. Syntax existing in typespecs that are missing in TypeCheck (e.g. `<<_::size>>`)
3. Syntax existing in Typecheck that does not exist in regular typespecs. I wouldn't really classify this as an issue. In some cases, it is completely necessary (e.g. named types, type guards) and other times it's kind of nice to have (e.g. `fixed_list`). It's just that the more differences there are with regular typespecs the harder it gets to keep straight which is which.

Anyway, not sure if any of that aligns with how you envision things, but just a couple more cents of feedback.

**Comment by Qqwy** [comment]
Thank you for your feedback! This is very helpful.

I agree with you with regard to the fixed-list syntax:
- Fixed lists are rather rare in Elixir code
- As such, they are not worth the extra friction caused by the difference between Elixir's typespecs and TypeCheck's syntax.

**Comment by baldwindavid** [comment]
Love the updates to the lists and their alignment to regular typespecs. Can this issue be closed out now?
